Close settings on clicking map for a width lesser than 1100px
adam-lynch/back-of-your-hand pull request #53
Opened 2023-03-18 11:57 UTC by Yogeshp0012

2023-03-18 13:46 UTC, adam-lynch requested changes
This is great, thanks!

2023-03-18 13:46 UTC, adam-lynch commented on source/Map.svelte
> +    if (innerWidth <= 1100) {
This confused me for a second;

```suggestion
    if (window.innerWidth <= 1100) {
```

2023-03-18 13:46 UTC, adam-lynch commented on source/Map.svelte
> +<div on:click={closeSettingsForSmallDevices} bind:this={mapElement} id="map" />
```suggestion
<div on:pointerdown={closeSettingsForSmallDevices} bind:this={mapElement} id="map" />
```

So it works when you zoom or pan the map on a touch device.

2023-03-18 13:46 UTC, adam-lynch commented on source/Map.svelte
> +      areSettingsShown.update((previous) => !previous);
```suggestion
      areSettingsShown.set(false);
```

2023-03-18 19:03 UTC, adam-lynch approved these changes

2023-03-18 19:03 UTC, merged

2023-03-18 19:03 UTC, adam-lynch commented
Thanks again!

2023-03-19 03:49 UTC, Yogeshp0012 commented
> Thanks again!

Ur welcome.

2024-07-25 18:54 UTC, adam-lynch commented
Hi @Yogeshp0012,

I hope you’re well. Thanks again for contributing, I really appreciate it.

## License Change

I’m currently overhauling this project and in doing that, I decided to change the license. Currently, it’s licensed under the [MIT License](https://choosealicense.com/licenses/mit/) and I am planning to re-license the project under the [Mozilla Public License 2.0 (MPL 2.0)](https://choosealicense.com/licenses/mpl-2.0/).

## Your consent

I would like your permission to re-license your contributions under MPL 2.0. All I ask is that you reply and confirm your consent. If you have any concerns or prefer not to re-license your contributions, please let me know (my email is on [my profile](https://github.com/adam-lynch/) if you would prefer that).

I will be re-licensing all of my contributions and will keep yours under MIT until you provide your consent to re-license them under MPL 2.0.

## Your contributions

All of your contributions are contained in this pull-request.

## Why MPL 2.0?

1. **File-Level Copyleft**: Ensures improvements are shared back with the community.
2. **Compatibility**: MPL 2.0 works well with other licenses, including GPL, allowing easier integration with larger projects.
3. **Contributor Management**: Provides clear guidelines for contributions and obligations.
4. **Patent Protection**: Offers explicit patent grants, protecting contributors from patent litigation.
5. **Balanced Copyleft**: Encourages open-source contributions while permitting use in proprietary projects under specific conditions.
6. **Corporate Adoption**: Aligns better with some corporate open-source policies.
7. **Clearer Compliance**: Known for precise language, making legal compliance simpler.

## More information

- [MIT License](https://choosealicense.com/licenses/mit/)
- [Mozilla Public License 2.0 (MPL 2.0)](https://choosealicense.com/licenses/mpl-2.0/)

Thank you!

2024-07-25 19:43 UTC, Yogeshp0012 commented
I acknowledge the request to change the license. You can proceed.

2024-07-26 08:16 UTC, adam-lynch commented
Thank you!