Add dynamic street exclusion feature
adam-lynch/back-of-your-hand pull request #62
Opened 2024-09-23 10:45 UTC by baso53

These changes enable adding a street exclusion dynamically once you submit the answer for a particular street. This is useful (for me at least  ) when using the app for exercise, so you can skip the streets you know in the future.

2024-09-25 18:43 UTC, adam-lynch commented
Hey thanks so much. Nice idea!

Forgive me but I'm very busy right now so I can't give it a proper review and run the code yet. In the meantime...

- Users should probably be able to reset/remove all exclusions right?
- Right now if you select an area and there are not enough streets, there's a message shown. Should that message be modified? Should it fill the remaining amount with excluded streets? (I doubt you'd want that)
- I'm surprised there could be duplicates. Was this always possible or is it related to your new code?

2024-09-26 19:44 UTC, baso53 commented
Thanks for the reply.

1. Yes, this would make the most sense. Do you think this would be okay to add in the settings panel?
2. I think the message is still okay. Maybe we could modify it to signify that the exclusions are taken into account, but in my opinion it's clear as it is now.
3. Depends on what you mean by duplicates. If you have a low number of questions selected, there is a high probability that the `getRandomItem` method will generate the same index multiple times, so the final question list for a round could have duplicates.

2024-10-05 14:41 UTC, adam-lynch requested changes
I found some time to review this in detail. Thanks again @baso53.

First, I'll respond to your last message...

> Yes, this would make the most sense. Do you think this would be okay to add in the settings panel?

Yes, I think a button in the settings panel should be fine. I.e. "Remove all custom exclusions" or "Reset custom exclusions". Maybe "Reset custom exclusions" would be better wording if it's always going to be there (even if you don't have any exclusions) 🤷 

>  I think the message is still okay. Maybe we could modify it to signify that the exclusions are taken into account, but in my opinion it's clear as it is now.

Ok, I don't mind leaving it as is.

> Depends on what you mean by duplicates. If you have a low number of questions selected, there is a high probability that the getRandomItem method will generate the same index multiple times, so the final question list for a round could have duplicates.

I looked into this and I don't think there can be duplicates. `pot` does not contain duplicates. Then every time we pick from the `pot` and add to `results`, we delete the item in `pot`. Therefore, it can't be picked twice.

Could you please undo any changes related to this de-duplication?

---

I added some comments with feedback on specific areas of the code. What you did is good, but I think it needs more changes to make it robust and safe enough to release to all users.

Sorry there will be a little bit more back and forth but I really appreciate you putting the time into this. It will be a nice addition for everyone plus I think it will improve some areas of the code too as a side-effect. Also, I'm happy to answer any questions / help if you are not sure how to do something.

---

One thing I didn't mention which will need to be done is to update the "Learn more" page (it's linked from the "Learn more" button). We can leave this until the end because it's easy and we haven't settled on how this will work exactly yet.

2024-10-05 14:41 UTC, adam-lynch commented on source/library/ContextPanel.svelte
> +      addExclusion({ name: $currentQuestion.target.name.toLowerCase() });
It's probably too risky to exclude solely based on name. People might play the game with different areas / size and we don't know why exactly they might choose to exclude a street. They might exclude a name which would match valid streets in future. I'd like to avoid that case.

I was trying to think of a way that we could store the exclusion as a combination of the name plus the area bounds or something like that. But I didn't come up with any idea that I really like.

Maybe the safest thing is to not try to be too smart here. Each element we get from OpenStreetMap has an ID. Maybe the exclusion should reference that ID. So I think this is what I'm suggesting:

- When the user clicks "exclude", take every OSM ID relating to the current "question" and add an exclusion for each. As you know, there could be multiple IDs because we combine them based on the name (in the current area bounds). For each ID, we put an exclusion in `localStorage`.
- When picking streets to put in a round, we combine / group streets together based on name. If *any* of those individual street have an ID which was previously excluded, do not include any of the streets in this in the round (i.e. any matching the name).

To do this, you'll probably have to update some other types, like the question would need to contain the OSM IDs of the streets (I'm 90% sure it doesn't contain that already). If you have any questions / need help, let me know.

To be clear, I'm saying the exclusion doesn't even _have_ to store anything else, but we might as well store the name because:

1. It's useful for debugging.
2. Maybe down the line (not now), we might allow users to see their exclusions.

2024-10-05 14:41 UTC, adam-lynch commented on source/library/ContextPanel.svelte
> +            </button>
Oh and whenever a user adds an exclusion (i.e. presses "Next" with the checkbox checked) or when they remove all exclusions, can you please send an event? E.g:

```
  const onStartClicked = async () => {
    await start();
    trackEvent({ name: "start", title: "Start" });
  };
```

` trackEvent({ name: "exclusion-added", title: "Exclusion added" });` is enough.

2025-08-03 16:46 UTC, adam-lynch commented
I'm going to close this because it's been a while and the codebase has changed a bit in the meantime. Happy to revisit this later but maybe give me a heads up first just in case. Thanks for your time

2025-08-03 16:46 UTC, closed without merging